version: "3.8"
services:
        backend:
            build:
                context: .
                dockerfile: Dockerfile1
            ports:
                - 8000:8000
            volumes:
                - .:/app
            depends_on:
                - db

        db:
            image: mysql:5.7.22
            container_name: db
            command: ['--ssl=0']
            #restart: always
            environment:
                MYSQL_DATABASE: admin
                MYSQL_USER: root
                MYSQL_PASSWORD: root
                MYSQL_ROOT_PASSWORD: root
                #OPTIONS': {ssl_mode: 'DISABLED'}
            volumes:
                - ./mysqldata:/var/lib/mysql
            ports:
                - 3306:3306